apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: api
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "256m"

---

kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    allow.http: "true"
spec:
  rules:
  - host: nodejs.erp-dev.de
    http:
      paths:
        - path: /
          backend:
            serviceName: api-service
            servicePort: 80